questions = {
    1: "Apakah anda sering mengalami buang air besar (lebih dari 2 kali)?",
    2: "Apakah anda mengalami berak encer?",
    3: "Apakah anda mengalami berak berdarah?",
    4: "Apakah anda merasa lesu dan tidak bergairah?",
    5: "Apakah anda tidak selera makan?",
    6: "Apakah anda merasa mual dan sering muntah (lebih dari 1 kali)?",
    7: "Apakah anda merasa sakit di bagian perut?",
    8: "Apakah tekanan darah anda rendah?",
    9: "Apakah anda merasa pusing?",
    10: "Apakah anda mengalami pingsan?",
    11: "Apakah suhu badan anda tinggi?",
    12: "Apakah anda mengalami luka di bagian tertentu?",
    13: "Apakah anda tidak dapat menggerakkan anggota badan tertentu?",
    14: "Apakah anda pernah memakan sesuatu?",
    15: "Apakah anda memakan daging?",
    16: "Apakah anda memakan jamur?",
    17: "Apakah anda memakan makanan kaleng?",
    18: "Apakah anda meminum susu?"
}
